server:
  port: 8001
spring:
  application:
    name: cloud-provier-hystrix-payment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http:eureka7001.com/eureka, http:eureka7002.com/eureka,
      #单机
        defaultZone: http://eureka7001.com:7001/eureka/